on:
  push:
    branches:
      - master

name: test

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.13'
      - name: Make tests
        run: make test
